### ISSUE TITLE
problem with Mac

### ISSUE THREAD

**Issue by kt6k** [epitools/epitools-matlab#1]
Hi.

I got a following message when I try to open "EpiTools_mac":

Unrecognized method, property, or field 'matlab' for class 'settings'.

Error in imshow (line 261)
    style = s.matlab.imshow.InitialMagnificationStyle.ActiveValue;

Error in EpiTools>handles_connection (line 181)
h = imshow(I(:,:,1:3), 'Parent', handles.axes8);

Error in EpiTools>EpiTools_OpeningFcn (line 142)
handles_connection(hObject,handles);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
    varargin{:});

Error in EpiTools (line 47)
    gui_mainfcn(gui_State, varargin{:});

**Comment by gattil** [comment]
I have the feeling that you are trying to run Epitools on an unsupported version of Matlab. 
EpiTools Graphic engine is not compatible with Matlab version above 2014a
https://epitools.github.io/wiki/Support/Known_Issues/
 
In case you cannot use a version of Matlab compatible with Epitools, I suggest you to check out the script version of Epitools 

- module_projection https://github.com/epitools/module_projection
- module_segmentation https://github.com/epitools/module_segmentation

Let me know if this helps you a little.
