### ISSUE TITLE
Problem with windows Epi-tools

### ISSUE THREAD

**Issue by XarlesSta** [epitools/epitools-matlab#2]
I keep having this issue when I try to open epi-tools in windows-machine: 

Error in imshow (line 256)
    style = s.matlab.imshow.InitialMagnificationStyle.ActiveValue;
Error in EpiTools>handles_connection (line 181)
h = imshow(I(:,:,1:3), 'Parent', handles.axes8);
Error in EpiTools>EpiTools_OpeningFcn (line 142)
handles_connection(hObject,handles);
Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});
Error in EpiTools (line 47)
    gui_mainfcn(gui_State, varargin{:});

**Comment by gattil** [comment]
I have the feeling that you are trying to run Epitools on an unsupported version of Matlab. 
EpiTools Graphic engine is not compatible with Matlab version above 2014a
https://epitools.github.io/wiki/Support/Known_Issues/
 
In case you cannot use a version of Matlab compatible with Epitools, I suggest you check out the script version of Epitools 

- module_projection https://github.com/epitools/module_projection
- module_segmentation https://github.com/epitools/module_segmentation

Let me know if this helps you a little.

**Comment by XarlesSta** [comment]
Thank you. You were right. I can work with Matlab2014a.

Sent from my iPad

On Aug 16, 2019, at 9:44 AM, Lorenzo Gatti <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the feeling that you are trying to run Epitools on an unsupported version of Matlab.
EpiTools Graphic engine is not compatible with Matlab version above 2014a
https://epitools.github.io/wiki/Support/Known_Issues/

In case you cannot use a version of Matlab compatible with Epitools, I suggest you check out the script version of Epitools

  *   module_projection https://github.com/epitools/module_projection
  *   module_segmentation https://github.com/epitools/module_segmentation

Let me know if this helps you a little.
